// DOCUMENT ACTIONS
const LOAD_DOCUMENTS = "DOCUMENTS_LOAD";
const SET_CURRENT_DOCUMENT = "SET_CURRENT_DOCUMENT";

// SEARCH ACTIONS
const SET_SEARCH_TEXT = "SET_SEARCH_TEXT";
const SET_SEARCH_TYPE = "SET_SEARCH_TEXT";

const actionTypes = {
  LOAD_DOCUMENTS,
  SET_CURRENT_DOCUMENT,
  SET_SEARCH_TEXT,
  SET_SEARCH_TYPE,
};

export default actionTypes;
