// DOCUMENT ACTIONS
const LOAD_DOCUMENTS = "DOCUMENTS_LOAD";
const SET_CURRENT_DOCUMENT = "SET_CURRENT_DOCUMENT";
const SET_FORM_VALUE = "SET_FORM_VALUE";
const SAVE_DOCUMENT = "SAVE_DOCUMENT";
const DELETE_DOCUMENT = "DELETE_DOCUMENT";

// SEARCH ACTIONS
const SET_SEARCH_TEXT = "SET_SEARCH_TEXT";
const SET_SEARCH_TYPE = "SET_SEARCH_TYPE";

// PAGINATION ACTIONS
const SET_PAGE = "SET_PAGE";

const actionTypes = {
  LOAD_DOCUMENTS,
  SET_CURRENT_DOCUMENT,
  SET_FORM_VALUE,
  SAVE_DOCUMENT,
  DELETE_DOCUMENT,
  SET_SEARCH_TEXT,
  SET_SEARCH_TYPE,
  SET_PAGE,
};

export default actionTypes;
